name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        
    - name: Install Android SDK and NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        mkdir -p ~/.buildozer/android/platform/android-sdk
        cd ~/.buildozer/android/platform/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools tools
        yes | ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses
        ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
        
    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
        ls -la bin/
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: oilprice-app
        path: bin/*.apk